name: YuppTV FTA JSON Saver

on:
  workflow_dispatch:
  schedule:
    - cron: '15 23 * * *'  # Runs every day at 5 AM

jobs:
  update-yupp-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and replace YuppTV data
        run: python yupp_fetch.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add yupp-fta.json
          git commit -m "Update YuppTV data - $(date -u +%Y-%m-%d)"  # Removed diff check
          git push
